workflows:
  my-workflow:
    environment:
      xcode: 12.5
      cocoapods: 1.10.2
      node: "^12.14.1 || >=14.0.0"
      npm: "^6.11.0 || ^7.5.6"
      xcode: 12.5
workflows:
  my-workflow:
    scripts:
      - name: Install dependencies
        script: sudo npm install --unsafe-perm -g node-sass 
      - name: Switch to a specific version of Cordova
        script: |
          set -e # exit on first failed command
          
          cvm install 9.0.0
          cvm use 9.0.0
      - name: Add iOS platform
        script: |
          set -e # exit on first failed command

          cordova platform remove ios --nosave
          cordova platform add ios --confirm --no-interactive --noresources --save
      - name: Build iOS release
        script: |
          set -e # exit on first failed command

          cordova build ios --no-interactive


